WORDS = {
    "Miasta": [
        {"word": "Paryż", "difficulty": "łatwe", "hint": "wieczorne światła"},
        {"word": "Londyn", "difficulty": "łatwe", "hint": "czerwona ikona"},
        {"word": "Rzym", "difficulty": "łatwe", "hint": "stare centrum"},
        {"word": "Nowy Jork", "difficulty": "średnie", "hint": "miasto nie śpi"},
        {"word": "Tokio", "difficulty": "średnie", "hint": "neony cisza"},
        {"word": "Sydney", "difficulty": "średnie", "hint": "biała fala"},
        {"word": "Dubaj", "difficulty": "średnie", "hint": "wysoko piasek"},
        {"word": "Berlin", "difficulty": "łatwe", "hint": "mur pamięć"},
        {"word": "Barcelona", "difficulty": "średnie", "hint": "kolory kształty"},
        {"word": "Moskwa", "difficulty": "średnie", "hint": "czerwone serce"},
        {"word": "Kair", "difficulty": "trudne", "hint": "pustynia cienie"},
        {"word": "Bangkok", "difficulty": "trudne", "hint": "ulice życie"},
        {"word": "Los Angeles", "difficulty": "średnie", "hint": "fabryka snów"},
        {"word": "Chicago", "difficulty": "średnie", "hint": "wiatr wieżowce"},
        {"word": "Amsterdam", "difficulty": "łatwe", "hint": "woda rowery"},
        {"word": "Wenecja", "difficulty": "łatwe", "hint": "bez dróg"},
        {"word": "Praga", "difficulty": "łatwe", "hint": "most zegar"},
        {"word": "Lizbona", "difficulty": "średnie", "hint": "żółte tramwaje"},
        {"word": "Seul", "difficulty": "trudne", "hint": "tech tradycja"},
        {"word": "Reykjavik", "difficulty": "ekstremalnie trudne", "hint": "zimna wyspa"}
    ],

    "Sport": [
        {"word": "Piłka nożna", "difficulty": "łatwe", "hint": "11 na 11"},
        {"word": "Koszykówka", "difficulty": "łatwe", "hint": "wysoko kosz"},
        {"word": "Tenis", "difficulty": "łatwe", "hint": "linie cisza"},
        {"word": "Siatkówka", "difficulty": "łatwe", "hint": "nad siatką"},
        {"word": "Boks", "difficulty": "średnie", "hint": "rundy walka"},
        {"word": "Szachy", "difficulty": "średnie", "hint": "ruch bez biegu"},
        {"word": "Golf", "difficulty": "średnie", "hint": "daleko precyzja"},
        {"word": "Hokej", "difficulty": "średnie", "hint": "lód kij"},
        {"word": "Narciarstwo", "difficulty": "średnie", "hint": "w dół szybko"},
        {"word": "Snowboard", "difficulty": "średnie", "hint": "jedna deska"},
        {"word": "Wspinaczka", "difficulty": "trudne", "hint": "bez drogi"},
        {"word": "Triathlon", "difficulty": "trudne", "hint": "trzy etapy"},
        {"word": "Rugby", "difficulty": "trudne", "hint": "przód chaos"},
        {"word": "Baseball", "difficulty": "trudne", "hint": "kij baza"},
        {"word": "Krykiet", "difficulty": "ekstremalnie trudne", "hint": "długi mecz"},
        {"word": "Curling", "difficulty": "ekstremalnie trudne", "hint": "szczotki lód"},
        {"word": "Badminton", "difficulty": "średnie", "hint": "lekki lot"},
        {"word": "Judo", "difficulty": "średnie", "hint": "siła przeciwnika"},
        {"word": "Karate", "difficulty": "średnie", "hint": "cios skupienie"},
        {"word": "F1", "difficulty": "łatwe", "hint": "maks prędkość"}
    ],

    "Filmy": [
        {"word": "Titanic", "difficulty": "łatwe", "hint": "za mało miejsca"},
        {"word": "Avatar", "difficulty": "łatwe", "hint": "niebieski świat"},
        {"word": "Matrix", "difficulty": "łatwe", "hint": "co prawdziwe"},
        {"word": "Gladiator", "difficulty": "średnie", "hint": "arena honor"},
        {"word": "Incepcja", "difficulty": "średnie", "hint": "sen w śnie"},
        {"word": "Interstellar", "difficulty": "średnie", "hint": "czas przestrzeń"},
        {"word": "Joker", "difficulty": "średnie", "hint": "śmiech bez radości"},
        {"word": "Batman", "difficulty": "łatwe", "hint": "noc symbol"},
        {"word": "Superman", "difficulty": "łatwe", "hint": "nie z ziemi"},
        {"word": "Shrek", "difficulty": "łatwe", "hint": "zielony bagna"},
        {"word": "Król Lew", "difficulty": "łatwe", "hint": "krąg życia"},
        {"word": "Harry Potter", "difficulty": "łatwe", "hint": "magiczna szkoła"},
        {"word": "Gwiezdne Wojny", "difficulty": "łatwe", "hint": "moc miecz"},
        {"word": "Deadpool", "difficulty": "średnie", "hint": "łamie zasady"},
        {"word": "Rocky", "difficulty": "średnie", "hint": "schody walka"},
        {"word": "Rambo", "difficulty": "średnie", "hint": "sam przeciw"},
        {"word": "Frozen", "difficulty": "łatwe", "hint": "zimne moce"},
        {"word": "Minionki", "difficulty": "łatwe", "hint": "żółty chaos"},
        {"word": "Oppenheimer", "difficulty": "trudne", "hint": "niszcząca siła"},
        {"word": "Parasite", "difficulty": "trudne", "hint": "dwa światy"}
    ],

    "Zawody": [
        {"word": "Lekarz", "difficulty": "łatwe", "hint": "decyzje szybko"},
        {"word": "Nauczyciel", "difficulty": "łatwe", "hint": "uczy innych"},
        {"word": "Policjant", "difficulty": "łatwe", "hint": "prawo ulice"},
        {"word": "Strażak", "difficulty": "łatwe", "hint": "ogień pomoc"},
        {"word": "Kucharz", "difficulty": "łatwe", "hint": "smak czas"},
        {"word": "Programista", "difficulty": "średnie", "hint": "kod ekran"},
        {"word": "Architekt", "difficulty": "średnie", "hint": "projekt przestrzeń"},
        {"word": "Pilot", "difficulty": "średnie", "hint": "nad chmurami"},
        {"word": "Prawnik", "difficulty": "średnie", "hint": "prawo słowa"},
        {"word": "Dziennikarz", "difficulty": "średnie", "hint": "pytania fakty"},
        {"word": "Mechanik", "difficulty": "łatwe", "hint": "naprawa maszyny"},
        {"word": "Fryzjer", "difficulty": "łatwe", "hint": "zmiana wyglądu"},
        {"word": "Psycholog", "difficulty": "trudne", "hint": "umysł rozmowa"},
        {"word": "Detektyw", "difficulty": "średnie", "hint": "szczegóły trop"},
        {"word": "Aktor", "difficulty": "łatwe", "hint": "gra role"},
        {"word": "Muzyk", "difficulty": "łatwe", "hint": "dźwięk rytm"},
        {"word": "Kierowca", "difficulty": "łatwe", "hint": "droga pojazd"},
        {"word": "Rolnik", "difficulty": "łatwe", "hint": "ziemia plony"},
        {"word": "Kosmonauta", "difficulty": "trudne", "hint": "kosmos daleko"},
        {"word": "Sędzia", "difficulty": "średnie", "hint": "ostateczna decyzja"}
    ],

    "Natura": [
        {"word": "Las", "difficulty": "łatwe", "hint": "dużo drzew"},
        {"word": "Rzeka", "difficulty": "łatwe", "hint": "ciągle płynie"},
        {"word": "Góra", "difficulty": "łatwe", "hint": "wysoko cisza"},
        {"word": "Morze", "difficulty": "łatwe", "hint": "bez końca"},
        {"word": "Pustynia", "difficulty": "średnie", "hint": "piasek brak"},
        {"word": "Wulkan", "difficulty": "średnie", "hint": "cisza wybuch"},
        {"word": "Burza", "difficulty": "łatwe", "hint": "błysk huk"},
        {"word": "Tęcza", "difficulty": "łatwe", "hint": "kolory niebo"},
        {"word": "Śnieg", "difficulty": "łatwe", "hint": "biała cisza"},
        {"word": "Wiatr", "difficulty": "łatwe", "hint": "niewidzialny ruch"},
        {"word": "Jezioro", "difficulty": "łatwe", "hint": "spokojna woda"},
        {"word": "Dżungla", "difficulty": "średnie", "hint": "gęsto dziko"},
        {"word": "Lodowiec", "difficulty": "trudne", "hint": "zimno powoli"},
        {"word": "Kanion", "difficulty": "trudne", "hint": "głęboka ziemia"},
        {"word": "Tornado", "difficulty": "trudne", "hint": "wir powietrza"},
        {"word": "Sawanna", "difficulty": "trudne", "hint": "trawa przestrzeń"},
        {"word": "Bagno", "difficulty": "średnie", "hint": "mokro grzęźnie"},
        {"word": "Klif", "difficulty": "średnie", "hint": "nagły spadek"},
        {"word": "Wyspa", "difficulty": "łatwe", "hint": "woda wokół"},
        {"word": "Gejzer", "difficulty": "ekstremalnie trudne", "hint": "gorąca woda"}
    ],

    "Technologia": [
        {"word": "Komputer", "difficulty": "łatwe", "hint": "liczy szybko"},
        {"word": "Telefon", "difficulty": "łatwe", "hint": "zawsze blisko"},
        {"word": "Internet", "difficulty": "łatwe", "hint": "łączy świat"},
        {"word": "Robot", "difficulty": "średnie", "hint": "nie człowiek"},
        {"word": "Sztuczna inteligencja", "difficulty": "średnie", "hint": "uczy się"},
        {"word": "Dron", "difficulty": "średnie", "hint": "lata kamera"},
        {"word": "Serwer", "difficulty": "trudne", "hint": "dane online"},
        {"word": "Kod", "difficulty": "łatwe", "hint": "ukryte znaczenie"},
        {"word": "Hasło", "difficulty": "łatwe", "hint": "tajny dostęp"},
        {"word": "Aplikacja", "difficulty": "łatwe", "hint": "małe narzędzie"},
        {"word": "Bluetooth", "difficulty": "średnie", "hint": "bez kabli"},
        {"word": "Chmura", "difficulty": "średnie", "hint": "dane niebo"},
        {"word": "Algorytm", "difficulty": "trudne", "hint": "kroki decyzje"},
        {"word": "Baza danych", "difficulty": "trudne", "hint": "dużo informacji"},
        {"word": "Cyberbezpieczeństwo", "difficulty": "ekstremalnie trudne", "hint": "ochrona danych"},
        {"word": "Firewall", "difficulty": "trudne", "hint": "blokuje dostęp"},
        {"word": "Sieć", "difficulty": "łatwe", "hint": "połączenia system"},
        {"word": "Laptop", "difficulty": "łatwe", "hint": "przenośny komputer"},
        {"word": "Tablet", "difficulty": "łatwe", "hint": "dotyk ekran"},
        {"word": "USB", "difficulty": "łatwe", "hint": "mały port"}
    ]
}