WORDS = {
    "Miasta": [
        {"word": "Paryż", "difficulty": "łatwe", "hint": "wieczorne światła"},
        {"word": "Londyn", "difficulty": "łatwe", "hint": "czerwona ikona"},
        {"word": "Rzym", "difficulty": "łatwe", "hint": "stare centrum"},
        {"word": "Nowy Jork", "difficulty": "średnie", "hint": "miasto nie śpi"},
        {"word": "Tokio", "difficulty": "średnie", "hint": "neony cisza"},
        {"word": "Sydney", "difficulty": "średnie", "hint": "biała fala"},
        {"word": "Dubaj", "difficulty": "średnie", "hint": "wysoko piasek"},
        {"word": "Berlin", "difficulty": "łatwe", "hint": "mur pamięć"},
        {"word": "Barcelona", "difficulty": "średnie", "hint": "kolory kształty"},
        {"word": "Moskwa", "difficulty": "średnie", "hint": "czerwone serce"},
        {"word": "Kair", "difficulty": "trudne", "hint": "pustynia cienie"},
        {"word": "Bangkok", "difficulty": "trudne", "hint": "ulice życie"},
        {"word": "Los Angeles", "difficulty": "średnie", "hint": "fabryka snów"},
        {"word": "Chicago", "difficulty": "średnie", "hint": "wiatr wieżowce"},
        {"word": "Amsterdam", "difficulty": "łatwe", "hint": "woda rowery"},
        {"word": "Wenecja", "difficulty": "łatwe", "hint": "bez dróg"},
        {"word": "Praga", "difficulty": "łatwe", "hint": "most zegar"},
        {"word": "Lizbona", "difficulty": "średnie", "hint": "żółte tramwaje"},
        {"word": "Seul", "difficulty": "trudne", "hint": "tech tradycja"},
        {"word": "Reykjavik", "difficulty": "ekstremalnie trudne", "hint": "zimna wyspa"}
    ],

    "Sport": [
        {"word": "Piłka nożna", "difficulty": "łatwe", "hint": "11 na 11"},
        {"word": "Koszykówka", "difficulty": "łatwe", "hint": "wysoko kosz"},
        {"word": "Tenis", "difficulty": "łatwe", "hint": "linie cisza"},
        {"word": "Siatkówka", "difficulty": "łatwe", "hint": "nad siatką"},
        {"word": "Boks", "difficulty": "średnie", "hint": "rundy walka"},
        {"word": "Szachy", "difficulty": "średnie", "hint": "ruch bez biegu"},
        {"word": "Golf", "difficulty": "średnie", "hint": "daleko precyzja"},
        {"word": "Hokej", "difficulty": "średnie", "hint": "lód kij"},
        {"word": "Narciarstwo", "difficulty": "średnie", "hint": "w dół szybko"},
        {"word": "Snowboard", "difficulty": "średnie", "hint": "jedna deska"},
        {"word": "Wspinaczka", "difficulty": "trudne", "hint": "bez drogi"},
        {"word": "Triathlon", "difficulty": "trudne", "hint": "trzy etapy"},
        {"word": "Rugby", "difficulty": "trudne", "hint": "przód chaos"},
        {"word": "Baseball", "difficulty": "trudne", "hint": "kij baza"},
        {"word": "Krykiet", "difficulty": "ekstremalnie trudne", "hint": "długi mecz"},
        {"word": "Curling", "difficulty": "ekstremalnie trudne", "hint": "szczotki lód"},
        {"word": "Badminton", "difficulty": "średnie", "hint": "lekki lot"},
        {"word": "Judo", "difficulty": "średnie", "hint": "siła przeciwnika"},
        {"word": "Karate", "difficulty": "średnie", "hint": "cios skupienie"},
        {"word": "F1", "difficulty": "łatwe", "hint": "maks prędkość"}
    ],

    "Filmy": [
        {"word": "Titanic", "difficulty": "łatwe", "hint": "za mało miejsca"},
        {"word": "Avatar", "difficulty": "łatwe", "hint": "niebieski świat"},
        {"word": "Matrix", "difficulty": "łatwe", "hint": "co prawdziwe"},
        {"word": "Gladiator", "difficulty": "średnie", "hint": "arena honor"},
        {"word": "Incepcja", "difficulty": "średnie", "hint": "sen w śnie"},
        {"word": "Interstellar", "difficulty": "średnie", "hint": "czas przestrzeń"},
        {"word": "Joker", "difficulty": "średnie", "hint": "śmiech bez radości"},
        {"word": "Batman", "difficulty": "łatwe", "hint": "noc symbol"},
        {"word": "Superman", "difficulty": "łatwe", "hint": "nie z ziemi"},
        {"word": "Shrek", "difficulty": "łatwe", "hint": "zielony bagna"},
        {"word": "Król Lew", "difficulty": "łatwe", "hint": "krąg życia"},
        {"word": "Harry Potter", "difficulty": "łatwe", "hint": "magiczna szkoła"},
        {"word": "Gwiezdne Wojny", "difficulty": "łatwe", "hint": "moc miecz"},
        {"word": "Deadpool", "difficulty": "średnie", "hint": "łamie zasady"},
        {"word": "Rocky", "difficulty": "średnie", "hint": "schody walka"},
        {"word": "Rambo", "difficulty": "średnie", "hint": "sam przeciw"},
        {"word": "Frozen", "difficulty": "łatwe", "hint": "zimne moce"},
        {"word": "Minionki", "difficulty": "łatwe", "hint": "żółty chaos"},
        {"word": "Oppenheimer", "difficulty": "trudne", "hint": "niszcząca siła"},
        {"word": "Parasite", "difficulty": "trudne", "hint": "dwa światy"}
    ],

    "Zawody": [
        {"word": "Lekarz", "difficulty": "łatwe", "hint": "decyzje szybko"},
        {"word": "Nauczyciel", "difficulty": "łatwe", "hint": "uczy innych"},
        {"word": "Policjant", "difficulty": "łatwe", "hint": "prawo ulice"},
        {"word": "Strażak", "difficulty": "łatwe", "hint": "ogień pomoc"},
        {"word": "Kucharz", "difficulty": "łatwe", "hint": "smak czas"},
        {"word": "Programista", "difficulty": "średnie", "hint": "kod ekran"},
        {"word": "Architekt", "difficulty": "średnie", "hint": "projekt przestrzeń"},
        {"word": "Pilot", "difficulty": "średnie", "hint": "nad chmurami"},
        {"word": "Prawnik", "difficulty": "średnie", "hint": "prawo słowa"},
        {"word": "Dziennikarz", "difficulty": "średnie", "hint": "pytania fakty"},
        {"word": "Mechanik", "difficulty": "łatwe", "hint": "naprawa maszyny"},
        {"word": "Fryzjer", "difficulty": "łatwe", "hint": "zmiana wyglądu"},
        {"word": "Psycholog", "difficulty": "trudne", "hint": "umysł rozmowa"},
        {"word": "Detektyw", "difficulty": "średnie", "hint": "szczegóły trop"},
        {"word": "Aktor", "difficulty": "łatwe", "hint": "gra role"},
        {"word": "Muzyk", "difficulty": "łatwe", "hint": "dźwięk rytm"},
        {"word": "Kierowca", "difficulty": "łatwe", "hint": "droga pojazd"},
        {"word": "Rolnik", "difficulty": "łatwe", "hint": "ziemia plony"},
        {"word": "Kosmonauta", "difficulty": "trudne", "hint": "kosmos daleko"},
        {"word": "Sędzia", "difficulty": "średnie", "hint": "ostateczna decyzja"}
    ],

    "Natura": [
        {"word": "Las", "difficulty": "łatwe", "hint": "dużo drzew"},
        {"word": "Rzeka", "difficulty": "łatwe", "hint": "ciągle płynie"},
        {"word": "Góra", "difficulty": "łatwe", "hint": "wysoko cisza"},
        {"word": "Morze", "difficulty": "łatwe", "hint": "bez końca"},
        {"word": "Pustynia", "difficulty": "średnie", "hint": "piasek brak"},
        {"word": "Wulkan", "difficulty": "średnie", "hint": "cisza wybuch"},
        {"word": "Burza", "difficulty": "łatwe", "hint": "błysk huk"},
        {"word": "Tęcza", "difficulty": "łatwe", "hint": "kolory niebo"},
        {"word": "Śnieg", "difficulty": "łatwe", "hint": "biała cisza"},
        {"word": "Wiatr", "difficulty": "łatwe", "hint": "niewidzialny ruch"},
        {"word": "Jezioro", "difficulty": "łatwe", "hint": "spokojna woda"},
        {"word": "Dżungla", "difficulty": "średnie", "hint": "gęsto dziko"},
        {"word": "Lodowiec", "difficulty": "trudne", "hint": "zimno powoli"},
        {"word": "Kanion", "difficulty": "trudne", "hint": "głęboka ziemia"},
        {"word": "Tornado", "difficulty": "trudne", "hint": "wir powietrza"},
        {"word": "Sawanna", "difficulty": "trudne", "hint": "trawa przestrzeń"},
        {"word": "Bagno", "difficulty": "średnie", "hint": "mokro grzęźnie"},
        {"word": "Klif", "difficulty": "średnie", "hint": "nagły spadek"},
        {"word": "Wyspa", "difficulty": "łatwe", "hint": "woda wokół"},
        {"word": "Gejzer", "difficulty": "ekstremalnie trudne", "hint": "gorąca woda"}
    ],

    "Technologia": [
        {"word": "Komputer", "difficulty": "łatwe", "hint": "liczy szybko"},
        {"word": "Telefon", "difficulty": "łatwe", "hint": "zawsze blisko"},
        {"word": "Internet", "difficulty": "łatwe", "hint": "łączy świat"},
        {"word": "Robot", "difficulty": "średnie", "hint": "nie człowiek"},
        {"word": "Sztuczna inteligencja", "difficulty": "średnie", "hint": "uczy się"},
        {"word": "Dron", "difficulty": "średnie", "hint": "lata kamera"},
        {"word": "Serwer", "difficulty": "trudne", "hint": "dane online"},
        {"word": "Kod", "difficulty": "łatwe", "hint": "ukryte znaczenie"},
        {"word": "Hasło", "difficulty": "łatwe", "hint": "tajny dostęp"},
        {"word": "Aplikacja", "difficulty": "łatwe", "hint": "małe narzędzie"},
        {"word": "Bluetooth", "difficulty": "średnie", "hint": "bez kabli"},
        {"word": "Chmura", "difficulty": "średnie", "hint": "dane niebo"},
        {"word": "Algorytm", "difficulty": "trudne", "hint": "kroki decyzje"},
        {"word": "Baza danych", "difficulty": "trudne", "hint": "dużo informacji"},
        {"word": "Cyberbezpieczeństwo", "difficulty": "ekstremalnie trudne", "hint": "ochrona danych"},
        {"word": "Firewall", "difficulty": "trudne", "hint": "blokuje dostęp"},
        {"word": "Sieć", "difficulty": "łatwe", "hint": "połączenia system"},
        {"word": "Laptop", "difficulty": "łatwe", "hint": "przenośny komputer"},
        {"word": "Tablet", "difficulty": "łatwe", "hint": "dotyk ekran"},
        {"word": "USB", "difficulty": "łatwe", "hint": "mały port"}
    ],
    "Codzienne": [
        {"word": "Kawa", "difficulty": "łatwe", "hint": "poranek energia"},
        {"word": "Prysznic", "difficulty": "łatwe", "hint": "ciepła woda"},
        {"word": "Budzik", "difficulty": "łatwe", "hint": "koniec snu"},
        {"word": "Klucze", "difficulty": "łatwe", "hint": "bez nich stoisz"},
        {"word": "Portfel", "difficulty": "łatwe", "hint": "zawsze znika"},
        {"word": "Lustro", "difficulty": "łatwe", "hint": "prawda odbicie"},
        {"word": "Telefon", "difficulty": "łatwe", "hint": "ciągle przy tobie"},
        {"word": "Łóżko", "difficulty": "łatwe", "hint": "trudno wstać"},
        {"word": "Okno", "difficulty": "łatwe", "hint": "świat za szybą"},
        {"word": "Drzwi", "difficulty": "łatwe", "hint": "wejście wyjście"},
        {"word": "Lodówka", "difficulty": "średnie", "hint": "zimne decyzje"},
        {"word": "Czajnik", "difficulty": "średnie", "hint": "zaraz będzie"},
        {"word": "Pilot", "difficulty": "średnie", "hint": "kto trzyma"},
        {"word": "Koc", "difficulty": "łatwe", "hint": "ciepło spokój"},
        {"word": "Szafa", "difficulty": "łatwe", "hint": "co na dziś"},
        {"word": "Zegar", "difficulty": "średnie", "hint": "ciągle ucieka"},
        {"word": "Światło", "difficulty": "łatwe", "hint": "ciemność znika"},
        {"word": "Ładowarka", "difficulty": "łatwe", "hint": "ratuje baterię"},
        {"word": "Poduszka", "difficulty": "łatwe", "hint": "miękki start"},
        {"word": "Dywan", "difficulty": "średnie", "hint": "pod stopami"}
    ],

    "Emocje": [
        {"word": "Strach", "difficulty": "łatwe", "hint": "coś za tobą"},
        {"word": "Radość", "difficulty": "łatwe", "hint": "uśmiech sam"},
        {"word": "Złość", "difficulty": "łatwe", "hint": "wybuch szybko"},
        {"word": "Smutek", "difficulty": "łatwe", "hint": "ciężko w środku"},
        {"word": "Zaskoczenie", "difficulty": "średnie", "hint": "tego nie było"},
        {"word": "Wstyd", "difficulty": "średnie", "hint": "chcesz zniknąć"},
        {"word": "Duma", "difficulty": "średnie", "hint": "to moje"},
        {"word": "Zazdrość", "difficulty": "średnie", "hint": "dlaczego on"},
        {"word": "Miłość", "difficulty": "łatwe", "hint": "więcej niż słowa"},
        {"word": "Nuda", "difficulty": "łatwe", "hint": "nic się nie dzieje"},
        {"word": "Stres", "difficulty": "średnie", "hint": "za dużo naraz"},
        {"word": "Spokój", "difficulty": "łatwe", "hint": "cisza w głowie"},
        {"word": "Tęsknota", "difficulty": "trudne", "hint": "kogoś brakuje"},
        {"word": "Ekscytacja", "difficulty": "średnie", "hint": "zaraz coś"},
        {"word": "Ulga", "difficulty": "średnie", "hint": "już po"},
        {"word": "Niepewność", "difficulty": "trudne", "hint": "co dalej"},
        {"word": "Zdziwienie", "difficulty": "łatwe", "hint": "serio to"},
        {"word": "Motywacja", "difficulty": "średnie", "hint": "działaj teraz"},
        {"word": "Rozczarowanie", "difficulty": "trudne", "hint": "miało być lepiej"},
        {"word": "Satysfakcja", "difficulty": "średnie", "hint": "dobrze zrobione"}
    ],

    "Internet": [
        {"word": "Mem", "difficulty": "łatwe", "hint": "śmieszny obraz"},
        {"word": "Like", "difficulty": "łatwe", "hint": "klik akceptacji"},
        {"word": "Follow", "difficulty": "łatwe", "hint": "idziesz za"},
        {"word": "Scroll", "difficulty": "łatwe", "hint": "bez końca"},
        {"word": "Hashtag", "difficulty": "łatwe", "hint": "krzyżyk słowa"},
        {"word": "TikTok", "difficulty": "łatwe", "hint": "krótkie wideo"},
        {"word": "Instagram", "difficulty": "łatwe", "hint": "idealne życie"},
        {"word": "YouTube", "difficulty": "łatwe", "hint": "wideo wszystko"},
        {"word": "Streamer", "difficulty": "średnie", "hint": "na żywo"},
        {"word": "Viral", "difficulty": "średnie", "hint": "wszędzie naraz"},
        {"word": "Clickbait", "difficulty": "średnie", "hint": "tytuł kłamie"},
        {"word": "Komentarz", "difficulty": "łatwe", "hint": "każdy ma zdanie"},
        {"word": "DM", "difficulty": "łatwe", "hint": "prywatna wiadomość"},
        {"word": "Ban", "difficulty": "łatwe", "hint": "koniec dostępu"},
        {"word": "Algorytm", "difficulty": "trudne", "hint": "decyduje co widzisz"},
        {"word": "Feed", "difficulty": "łatwe", "hint": "ciąg postów"},
        {"word": "Subskrypcja", "difficulty": "średnie", "hint": "chcesz więcej"},
        {"word": "Avatar", "difficulty": "łatwe", "hint": "twoje online ja"},
        {"word": "GIF", "difficulty": "łatwe", "hint": "ruchomy obraz"},
        {"word": "Trend", "difficulty": "łatwe", "hint": "wszyscy robią"}
    ],

    "Jedzenie": [
        {"word": "Pizza", "difficulty": "łatwe", "hint": "okrągły klasyk"},
        {"word": "Burger", "difficulty": "łatwe", "hint": "mięso bułka"},
        {"word": "Frytki", "difficulty": "łatwe", "hint": "zawsze obok"},
        {"word": "Lody", "difficulty": "łatwe", "hint": "zimna przyjemność"},
        {"word": "Czekolada", "difficulty": "łatwe", "hint": "słodkie uzależnienie"},
        {"word": "Makaron", "difficulty": "łatwe", "hint": "długie nitki"},
        {"word": "Ryż", "difficulty": "łatwe", "hint": "małe ziarna"},
        {"word": "Sushi", "difficulty": "średnie", "hint": "surowa precyzja"},
        {"word": "Kebab", "difficulty": "łatwe", "hint": "nocny wybór"},
        {"word": "Sałatka", "difficulty": "łatwe", "hint": "lekka opcja"},
        {"word": "Zupa", "difficulty": "łatwe", "hint": "łyżka ciepło"},
        {"word": "Stek", "difficulty": "średnie", "hint": "krwisty wybór"},
        {"word": "Ser", "difficulty": "łatwe", "hint": "żółty blok"},
        {"word": "Chleb", "difficulty": "łatwe", "hint": "podstawa wszystkiego"},
        {"word": "Jajko", "difficulty": "łatwe", "hint": "początek życia"},
        {"word": "Tort", "difficulty": "łatwe", "hint": "świeczki okazja"},
        {"word": "Pączek", "difficulty": "łatwe", "hint": "dziura środek"},
        {"word": "Pierogi", "difficulty": "łatwe", "hint": "polski klasyk"},
        {"word": "Hot dog", "difficulty": "łatwe", "hint": "szybka bułka"},
        {"word": "Popcorn", "difficulty": "łatwe", "hint": "kino chrupanie"}
    ],

    "Miejsca": [
        {"word": "Szkoła", "difficulty": "łatwe", "hint": "nie chce się"},
        {"word": "Dom", "difficulty": "łatwe", "hint": "bezpieczne miejsce"},
        {"word": "Sklep", "difficulty": "łatwe", "hint": "zawsze coś kupisz"},
        {"word": "Park", "difficulty": "łatwe", "hint": "zielono cisza"},
        {"word": "Siłownia", "difficulty": "łatwe", "hint": "ból mięśnie"},
        {"word": "Kino", "difficulty": "łatwe", "hint": "ciemno ekran"},
        {"word": "Restauracja", "difficulty": "łatwe", "hint": "nie gotujesz"},
        {"word": "Plaża", "difficulty": "łatwe", "hint": "piasek słońce"},
        {"word": "Lotnisko", "difficulty": "średnie", "hint": "start podróży"},
        {"word": "Szpital", "difficulty": "średnie", "hint": "nie chcesz tu"},
        {"word": "Hotel", "difficulty": "łatwe", "hint": "na chwilę"},
        {"word": "Las", "difficulty": "łatwe", "hint": "dużo drzew"},
        {"word": "Klub", "difficulty": "łatwe", "hint": "noc muzyka"},
        {"word": "Biblioteka", "difficulty": "średnie", "hint": "cisza wiedza"},
        {"word": "Stadion", "difficulty": "łatwe", "hint": "tłum emocje"},
        {"word": "Dworzec", "difficulty": "średnie", "hint": "czekanie odjazd"},
        {"word": "Basen", "difficulty": "łatwe", "hint": "woda tor"},
        {"word": "Góry", "difficulty": "łatwe", "hint": "wysoko trudniej"},
        {"word": "Muzeum", "difficulty": "średnie", "hint": "stare rzeczy"},
        {"word": "Ulica", "difficulty": "łatwe", "hint": "ciągły ruch"}
    ]
}