WORDS = {

"Podstawowe łatwe": [
{"word":"Warszawa","category":"Miasta","hint":"syrenka"},
{"word":"Kraków","category":"Miasta","hint":"rynek"},
{"word":"Gdańsk","category":"Miasta","hint":"stocznia"},
{"word":"Berlin","category":"Miasta","hint":"mur"},
{"word":"Paryż","category":"Miasta","hint":"wieża"},
{"word":"Rzym","category":"Miasta","hint":"koloseum"},
{"word":"Londyn","category":"Miasta","hint":"bigben"},
{"word":"Madryt","category":"Miasta","hint":"real"},
{"word":"Praga","category":"Miasta","hint":"most"},
{"word":"Wiedeń","category":"Miasta","hint":"opera"},

{"word":"Pizza","category":"Jedzenie","hint":"ser"},
{"word":"Burger","category":"Jedzenie","hint":"bułka"},
{"word":"Frytki","category":"Jedzenie","hint":"sól"},
{"word":"Hot dog","category":"Jedzenie","hint":"parówka"},
{"word":"Kanapka","category":"Jedzenie","hint":"chleb"},
{"word":"Makaron","category":"Jedzenie","hint":"nitki"},
{"word":"Ryż","category":"Jedzenie","hint":"ziarno"},
{"word":"Zupa","category":"Jedzenie","hint":"łyżka"},
{"word":"Jabłko","category":"Jedzenie","hint":"sad"},
{"word":"Banan","category":"Jedzenie","hint":"skórka"},

{"word":"Kot","category":"Zwierzęta","hint":"mruk"},
{"word":"Pies","category":"Zwierzęta","hint":"ogon"},
{"word":"Krowa","category":"Zwierzęta","hint":"mleko"},
{"word":"Koń","category":"Zwierzęta","hint":"galop"},
{"word":"Świnia","category":"Zwierzęta","hint":"błoto"},
{"word":"Owca","category":"Zwierzęta","hint":"wełna"},
{"word":"Kura","category":"Zwierzęta","hint":"jajo"},
{"word":"Kaczka","category":"Zwierzęta","hint":"staw"},
{"word":"Mysz","category":"Zwierzęta","hint":"ser"},
{"word":"Ryba","category":"Zwierzęta","hint":"woda"},

{"word":"Piłka nożna","category":"Sporty","hint":"gol"},
{"word":"Koszykówka","category":"Sporty","hint":"kosz"},
{"word":"Siatkówka","category":"Sporty","hint":"plaża"},
{"word":"Tenis","category":"Sporty","hint":"rakieta"},
{"word":"Bieganie","category":"Sporty","hint":"buty"},
{"word":"Pływanie","category":"Sporty","hint":"basen"},
{"word":"Rower","category":"Sporty","hint":"łańcuch"},
{"word":"Narciarstwo","category":"Sporty","hint":"stok"},
{"word":"Skoki","category":"Sporty","hint":"belka"},
{"word":"Ping pong","category":"Sporty","hint":"stół"},

{"word":"Sanah","category":"Muzyka","hint":"radio"},
{"word":"Kizo","category":"Muzyka","hint":"trap"},
{"word":"Bedoes","category":"Muzyka","hint":"rap"},
{"word":"Mata","category":"Muzyka","hint":"szkoła"},
{"word":"Quebonafide","category":"Muzyka","hint":"tatuaże"},
{"word":"Taco Hemingway","category":"Muzyka","hint":"miasto"},
{"word":"Dawid Podsiadło","category":"Muzyka","hint":"głos"},
{"word":"The Weeknd","category":"Muzyka","hint":"blinding"},
{"word":"Drake","category":"Muzyka","hint":"kanada"},
{"word":"Rihanna","category":"Muzyka","hint":"umbrella"},

{"word":"Szkoła","category":"Miejsca","hint":"lekcja"},
{"word":"Dom","category":"Miejsca","hint":"łóżko"},
{"word":"Sklep","category":"Miejsca","hint":"kasa"},
{"word":"Basen","category":"Miejsca","hint":"woda"},
{"word":"Park","category":"Miejsca","hint":"ławka"},
{"word":"Kino","category":"Miejsca","hint":"ekran"},
{"word":"Restauracja","category":"Miejsca","hint":"menu"},
{"word":"Szpital","category":"Miejsca","hint":"lekarz"},
{"word":"Siłownia","category":"Miejsca","hint":"hantle"},
{"word":"Biblioteka","category":"Miejsca","hint":"cisza"},

{"word":"Kubek","category":"Przedmioty","hint":"herbata"},
{"word":"Talerz","category":"Przedmioty","hint":"obiad"},
{"word":"Łyżka","category":"Przedmioty","hint":"zupa"},
{"word":"Widelec","category":"Przedmioty","hint":"kolce"},
{"word":"Pilot","category":"Przedmioty","hint":"tv"},
{"word":"Telefon","category":"Przedmioty","hint":"ekran"},
{"word":"Laptop","category":"Przedmioty","hint":"klawiatura"},
{"word":"Krzesło","category":"Przedmioty","hint":"siedzenie"},
{"word":"Stół","category":"Przedmioty","hint":"blat"},
{"word":"Plecak","category":"Przedmioty","hint":"szkoła"}
],


"Podstawowe średnie": [
{"word":"Radom","category":"Miasta","hint":"lotnisko"},
{"word":"Poznań","category":"Miasta","hint":"koziołki"},
{"word":"Szczecin","category":"Miasta","hint":"port"},
{"word":"Lublin","category":"Miasta","hint":"wschód"},
{"word":"Katowice","category":"Miasta","hint":"śląsk"},
{"word":"Oslo","category":"Miasta","hint":"fiord"},
{"word":"Dublin","category":"Miasta","hint":"piwo"},
{"word":"Ateny","category":"Miasta","hint":"ruiny"},
{"word":"Lizbona","category":"Miasta","hint":"tramwaj"},
{"word":"Zagrzeb","category":"Miasta","hint":"bałkany"},

{"word":"Sushi","category":"Jedzenie","hint":"ryż"},
{"word":"Kebab","category":"Jedzenie","hint":"mięso"},
{"word":"Naleśniki","category":"Jedzenie","hint":"patelnia"},
{"word":"Tosty","category":"Jedzenie","hint":"opiekacz"},
{"word":"Pierogi","category":"Jedzenie","hint":"lepienie"},
{"word":"Sałatka","category":"Jedzenie","hint":"mieszanie"},
{"word":"Omlet","category":"Jedzenie","hint":"jajko"},
{"word":"Rosół","category":"Jedzenie","hint":"niedziela"},
{"word":"Tort","category":"Jedzenie","hint":"świeczki"},
{"word":"Lody","category":"Jedzenie","hint":"zimno"},

{"word":"Delfin","category":"Zwierzęta","hint":"inteligencja"},
{"word":"Lew","category":"Zwierzęta","hint":"grzywa"},
{"word":"Tygrys","category":"Zwierzęta","hint":"paski"},
{"word":"Słoń","category":"Zwierzęta","hint":"trąba"},
{"word":"Żyrafa","category":"Zwierzęta","hint":"szyja"},
{"word":"Wilk","category":"Zwierzęta","hint":"wataha"},
{"word":"Lis","category":"Zwierzęta","hint":"rudy"},
{"word":"Zebra","category":"Zwierzęta","hint":"pasy"},
{"word":"Pingwin","category":"Zwierzęta","hint":"lód"},
{"word":"Rekin","category":"Zwierzęta","hint":"zęby"},

{"word":"Siatkówka","category":"Sporty","hint":"blok"},
{"word":"Tenis","category":"Sporty","hint":"serwis"},
{"word":"Boks","category":"Sporty","hint":"ring"},
{"word":"F1","category":"Sporty","hint":"bolid"},
{"word":"Hokej","category":"Sporty","hint":"krążek"},
{"word":"Golf","category":"Sporty","hint":"dołek"},
{"word":"Rugby","category":"Sporty","hint":"kontakt"},
{"word":"Szachy","category":"Sporty","hint":"król"},
{"word":"Bilard","category":"Sporty","hint":"kule"},
{"word":"Skateboarding","category":"Sporty","hint":"deska"},

{"word":"Young Leosia","category":"Muzyka","hint":"impreza"},
{"word":"White 2115","category":"Muzyka","hint":"chill"},
{"word":"Malik Montana","category":"Muzyka","hint":"gang"},
{"word":"Szpaku","category":"Muzyka","hint":"mrok"},
{"word":"Jan-Rapowanie","category":"Muzyka","hint":"flow"},
{"word":"Harry Styles","category":"Muzyka","hint":"styl"},
{"word":"Billie Eilish","category":"Muzyka","hint":"szept"},
{"word":"Dua Lipa","category":"Muzyka","hint":"dance"},
{"word":"Post Malone","category":"Muzyka","hint":"tatuaże"},
{"word":"Travis Scott","category":"Muzyka","hint":"astro"},

{"word":"Lotnisko","category":"Miejsca","hint":"start"},
{"word":"Stadion","category":"Miejsca","hint":"trybuny"},
{"word":"Dworzec","category":"Miejsca","hint":"peron"},
{"word":"Hotel","category":"Miejsca","hint":"nocleg"},
{"word":"Muzeum","category":"Miejsca","hint":"eksponat"},
{"word":"Zoo","category":"Miejsca","hint":"klatki"},
{"word":"Teatr","category":"Miejsca","hint":"scena"},
{"word":"Kościół","category":"Miejsca","hint":"ołtarz"},
{"word":"Uniwersytet","category":"Miejsca","hint":"wykład"},
{"word":"Galeria","category":"Miejsca","hint":"zakupy"},

{"word":"Słuchawki","category":"Przedmioty","hint":"uszy"},
{"word":"Klawiatura","category":"Przedmioty","hint":"pisanie"},
{"word":"Myszka","category":"Przedmioty","hint":"klik"},
{"word":"Ładowarka","category":"Przedmioty","hint":"prąd"},
{"word":"Poduszka","category":"Przedmioty","hint":"sen"},
{"word":"Kołdra","category":"Przedmioty","hint":"ciepło"},
{"word":"Szczoteczka","category":"Przedmioty","hint":"zęby"},
{"word":"Lustro","category":"Przedmioty","hint":"odbicie"},
{"word":"Zegar","category":"Przedmioty","hint":"czas"},
{"word":"Kabel","category":"Przedmioty","hint":"łącze"}
],



"Podstawowe trudne": [

# Miasta
{"word":"Brno","category":"Miasta","hint":"czechy"},
{"word":"Salzburg","category":"Miasta","hint":"mozart"},
{"word":"Innsbruck","category":"Miasta","hint":"alpy"},
{"word":"Nicea","category":"Miasta","hint":"lazurowe"},
{"word":"Marsylia","category":"Miasta","hint":"port"},
{"word":"Turyn","category":"Miasta","hint":"fiat"},
{"word":"Neapol","category":"Miasta","hint":"wulkan"},
{"word":"Bolonia","category":"Miasta","hint":"makaron"},
{"word":"Florencja","category":"Miasta","hint":"renesans"},
{"word":"Monachium","category":"Miasta","hint":"piwo"},

# Jedzenie
{"word":"Carbonara","category":"Jedzenie","hint":"bekon"},
{"word":"Lasagne","category":"Jedzenie","hint":"warstwy"},
{"word":"Gnocchi","category":"Jedzenie","hint":"kluski"},
{"word":"Risotto","category":"Jedzenie","hint":"kremowe"},
{"word":"Ramen","category":"Jedzenie","hint":"bulion"},
{"word":"Tatar","category":"Jedzenie","hint":"surowe"},
{"word":"Falafel","category":"Jedzenie","hint":"ciecierzyca"},
{"word":"Burrito","category":"Jedzenie","hint":"zawinięte"},
{"word":"Nachosy","category":"Jedzenie","hint":"chrupki"},
{"word":"Guacamole","category":"Jedzenie","hint":"awokado"},

# Zwierzęta
{"word":"Gepard","category":"Zwierzęta","hint":"szybkość"},
{"word":"Pantera","category":"Zwierzęta","hint":"ciemna"},
{"word":"Jaguar","category":"Zwierzęta","hint":"dżungla"},
{"word":"Puma","category":"Zwierzęta","hint":"skok"},
{"word":"Hiena","category":"Zwierzęta","hint":"śmiech"},
{"word":"Koala","category":"Zwierzęta","hint":"eukaliptus"},
{"word":"Kangur","category":"Zwierzęta","hint":"torba"},
{"word":"Lemur","category":"Zwierzęta","hint":"oczy"},
{"word":"Bizon","category":"Zwierzęta","hint":"rogi"},
{"word":"Żubr","category":"Zwierzęta","hint":"puszcza"},

# Sporty
{"word":"Boks","category":"Sporty","hint":"cios"},
{"word":"MMA","category":"Sporty","hint":"klatka"},
{"word":"F1","category":"Sporty","hint":"tor"},
{"word":"Hokej","category":"Sporty","hint":"lód"},
{"word":"Golf","category":"Sporty","hint":"green"},
{"word":"Rugby","category":"Sporty","hint":"kontakt"},
{"word":"Szachy","category":"Sporty","hint":"strategia"},
{"word":"Bilard","category":"Sporty","hint":"kije"},
{"word":"Snooker","category":"Sporty","hint":"kolory"},
{"word":"Darts","category":"Sporty","hint":"tarcza"},

# Muzyka
{"word":"Szpaku","category":"Muzyka","hint":"ciemność"},
{"word":"OKI","category":"Muzyka","hint":"flow"},
{"word":"Otsochodzi","category":"Muzyka","hint":"melodia"},
{"word":"PRO8L3M","category":"Muzyka","hint":"noc"},
{"word":"Paluch","category":"Muzyka","hint":"ulica"},
{"word":"Lil Nas X","category":"Muzyka","hint":"cowboy"},
{"word":"Doja Cat","category":"Muzyka","hint":"cat"},
{"word":"Kendrick Lamar","category":"Muzyka","hint":"pulitzer"},
{"word":"J Cole","category":"Muzyka","hint":"dreamville"},
{"word":"Future","category":"Muzyka","hint":"autotune"},

# Miejsca
{"word":"Planetarium","category":"Miejsca","hint":"gwiazdy"},
{"word":"Akwarium","category":"Miejsca","hint":"ryby"},
{"word":"Laboratorium","category":"Miejsca","hint":"chemia"},
{"word":"Warsztat","category":"Miejsca","hint":"narzędzia"},
{"word":"Fabryka","category":"Miejsca","hint":"produkcja"},
{"word":"Ratusz","category":"Miejsca","hint":"urząd"},
{"word":"Ambasada","category":"Miejsca","hint":"flaga"},
{"word":"Archiwum","category":"Miejsca","hint":"dokumenty"},
{"word":"Elektrownia","category":"Miejsca","hint":"energia"},
{"word":"Stocznia","category":"Miejsca","hint":"statki"},

# Przedmioty
{"word":"Pendrive","category":"Przedmioty","hint":"usb"},
{"word":"Projektor","category":"Przedmioty","hint":"obraz"},
{"word":"Router","category":"Przedmioty","hint":"wifi"},
{"word":"Mikrofon","category":"Przedmioty","hint":"głos"},
{"word":"Statyw","category":"Przedmioty","hint":"stabilność"},
{"word":"Parasol","category":"Przedmioty","hint":"deszcz"},
{"word":"Termos","category":"Przedmioty","hint":"ciepło"},
{"word":"Kalkulator","category":"Przedmioty","hint":"liczby"},
{"word":"Notatnik","category":"Przedmioty","hint":"kartki"},
{"word":"Adapter","category":"Przedmioty","hint":"przejście"}
],



"Podstawowe ekstremalnie trudne": [

# Miasta 
{"word":"Kijów","category":"Miasta","hint":"dnipro"},
{"word":"Oslo","category":"Miasta","hint":"fiord"},
{"word":"Sztokholm","category":"Miasta","hint":"wyspy"},
{"word":"Helsinki","category":"Miasta","hint":"zimno"},
{"word":"Ryga","category":"Miasta","hint":"łotwa"},
{"word":"Wilno","category":"Miasta","hint":"litwa"},
{"word":"Tallin","category":"Miasta","hint":"średniowiecze"},
{"word":"Bruksela","category":"Miasta","hint":"unia"},
{"word":"Genewa","category":"Miasta","hint":"banki"},
{"word":"Zurych","category":"Miasta","hint":"szwajcaria"},

# Jedzenie 
{"word":"Qurrito","category":"Jedzenie","hint":"quesadilla"},
{"word":"Tortilla","category":"Jedzenie","hint":"zawijanie"},
{"word":"Focaccia","category":"Jedzenie","hint":"oliwa"},
{"word":"Mozzarella","category":"Jedzenie","hint":"kulki"},
{"word":"Bruschetta","category":"Jedzenie","hint":"grzanki"},
{"word":"Panna cotta","category":"Jedzenie","hint":"deser"},
{"word":"Tiramisu","category":"Jedzenie","hint":"kawa"},
{"word":"Pad thai","category":"Jedzenie","hint":"makaron"},
{"word":"Gyoza","category":"Jedzenie","hint":"pierogi"},
{"word":"Bao","category":"Jedzenie","hint":"bułeczki"},

# Zwierzęta
{"word":"Dziobak","category":"Zwierzęta","hint":"dziwny"},
{"word":"Narwal","category":"Zwierzęta","hint":"róg"},
{"word":"Kapibara","category":"Zwierzęta","hint":"spokój"},
{"word":"Tapir","category":"Zwierzęta","hint":"nos"},
{"word":"Okapi","category":"Zwierzęta","hint":"paski"},
{"word":"Fretka","category":"Zwierzęta","hint":"domowa"},
{"word":"Szop","category":"Zwierzęta","hint":"maska"},
{"word":"Borsuk","category":"Zwierzęta","hint":"nora"},
{"word":"Rosomak","category":"Zwierzęta","hint":"agresja"},
{"word":"Pangolin","category":"Zwierzęta","hint":"łuski"},

# Sporty
{"word":"Curling","category":"Sporty","hint":"kamień"},
{"word":"Snooker","category":"Sporty","hint":"precyzja"},
{"word":"Squash","category":"Sporty","hint":"ściana"},
{"word":"Badminton","category":"Sporty","hint":"lotka"},
{"word":"Lacrosse","category":"Sporty","hint":"siatka"},
{"word":"Kitesurfing","category":"Sporty","hint":"wiatr"},
{"word":"Wakeboard","category":"Sporty","hint":"lina"},
{"word":"Parkour","category":"Sporty","hint":"miasto"},
{"word":"Triathlon","category":"Sporty","hint":"3 etapy"},
{"word":"Esport","category":"Sporty","hint":"komputer"},

# Muzyka
{"word":"Yeat","category":"Muzyka","hint":"rage"},
{"word":"Central Cee","category":"Muzyka","hint":"uk"},
{"word":"Jack Harlow","category":"Muzyka","hint":"flow"},
{"word":"Lil Baby","category":"Muzyka","hint":"trap"},
{"word":"Gunna","category":"Muzyka","hint":"slime"},
{"word":"Don Toliver","category":"Muzyka","hint":"astro"},
{"word":"SZA","category":"Muzyka","hint":"rnb"},
{"word":"Doja Cat","category":"Muzyka","hint":"viral"},
{"word":"Ice Spice","category":"Muzyka","hint":"munch"},
{"word":"PinkPantheress","category":"Muzyka","hint":"ukg"},

# Miejsca
{"word":"Obserwatorium","category":"Miejsca","hint":"teleskop"},
{"word":"Serwerownia","category":"Miejsca","hint":"szafy"},
{"word":"Hangar","category":"Miejsca","hint":"samoloty"},
{"word":"Bunkier","category":"Miejsca","hint":"schron"},
{"word":"Stocznia","category":"Miejsca","hint":"kadłub"},
{"word":"Rafineria","category":"Miejsca","hint":"ropa"},
{"word":"Mennica","category":"Miejsca","hint":"monety"},
{"word":"Latarnia","category":"Miejsca","hint":"światło"},
{"word":"Terminal","category":"Miejsca","hint":"odlot"},
{"word":"Radiostacja","category":"Miejsca","hint":"sygnał"},

# Przedmioty
{"word":"Oscyloskop","category":"Przedmioty","hint":"fala"},
{"word":"Kompas","category":"Przedmioty","hint":"kierunek"},
{"word":"Dalmierz","category":"Przedmioty","hint":"odległość"},
{"word":"Lutownica","category":"Przedmioty","hint":"ciepło"},
{"word":"Żyroskop","category":"Przedmioty","hint":"balans"},
{"word":"Antena","category":"Przedmioty","hint":"sygnał"},
{"word":"Przekaźnik","category":"Przedmioty","hint":"prąd"},
{"word":"Radiotelefon","category":"Przedmioty","hint":"łączność"},
{"word":"Woltomierz","category":"Przedmioty","hint":"napięcie"},
{"word":"Amperomierz","category":"Przedmioty","hint":"prąd"}
]
}